---
title: "Analisis de los empleados de Baltimore"
author: "Maria Castellanos"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#borrar todas las variables
rm(list = ls())

```

# Importamos datos con Rbase

```{r}
rutaFichero <- "data/Baltimore_City_Employee_Salaries.csv"
datosRbase <- read.csv("data/Baltimore_City_Employee_Salaries.csv")
View(datosRbase)


```

# Importamos datos con Readr

```{r}
library(readr)
datosReadr <- read_csv("data/Baltimore_City_Employee_Salaries.csv", col_types = cols(hireDate = col_date(format = "%Y-%m-%d")))
View(datosReadr)

```

# Importamos con Rio

```{r}
library(rio)
datosRio <- import(file  = "data/Baltimore_City_Employee_Salaries.csv")
View(datosRio)

```

# Leemos el fichero linea a linea

```{r}
readr::guess_encoding("data/Baltimore_City_Employee_Salaries.csv")

fichero = "data/Baltimore_City_Employee_Salaries.csv"

f = file(fichero, encoding = "ASCII")
datos <- readline(con  = f)


```

# en SQL

```{r}
library(RMySQL) 

#Conexión 
mysqlconnection = dbConnect(RMySQL::MySQL(), dbname='employees', host='oceano.uv.es', 
port=3306, user='datamecum',password='ford') 

#Información 
dbGetInfo(mysqlconnection) 

# Tablas contenidas en la BBDD 
dbListTables(mysqlconnection) 

# Descarga de tablas --> data.frame 
salarios<-dbReadTable(mysqlconnection,name = 'salaries') 
empleados<-dbReadTable(mysqlconnection,name = 'employees') 



# Realizamos una consulta SQL en la BBDD (sin descargar) 
result = dbSendQuery(mysqlconnection, "select * from employees") 

# Descargamos los n (5) elementos resultantes de la consulta 
data.frame = dbFetch(result, n = 5) 

# Librera y finaliza la consulta 
dbClearResult(result)

```
